package ar.com.softarte.model;
// Generated 28-mar-2014 22:03:42 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name = "compra", schema = "public")
public class Compra implements java.io.Serializable {

	private int id;
	private MateriaPrima materiaPrima;
	private Double precio;
	private Date fecha;
	private Double cantidad;

	public Compra() {
	}

	public Compra(int id) {
		this.id = id;
	}

	public Compra(int id, MateriaPrima materiaPrima, Double precio, Date fecha,
			Double cantidad) {
		this.id = id;
		this.materiaPrima = materiaPrima;
		this.precio = precio;
		this.fecha = fecha;
		this.cantidad = cantidad;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="compra_id_seq")
    @SequenceGenerator(name="compra_id_seq", sequenceName="compra_id_seq", allocationSize=1)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne()
	@JoinColumn(name = "id_materia_prima")
	public MateriaPrima getMateriaPrima() {
		return this.materiaPrima;
	}

	public void setMateriaPrima(MateriaPrima materiaPrima) {
		this.materiaPrima = materiaPrima;
	}

	@Column(name = "precio", precision = 17, scale = 17)
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "cantidad", precision = 17, scale = 17)
	public Double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

}
