package ar.com.softarte.model;
// Generated 02-mar-2014 13:46:55 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * IngredientesProducto generated by hbm2java
 */
@Entity
@Table(name = "ingredientes_producto", schema = "public")
public class IngredientesProducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -40902887134915934L;
	private int id;
	private MateriaPrima materiaPrima;
	private Producto producto;
	private Double cantidad;

	public IngredientesProducto() {
	}

	public IngredientesProducto(int id, MateriaPrima materiaPrima,
			Producto producto) {
		this.id = id;
		this.materiaPrima = materiaPrima;
		this.producto = producto;
	}

	public IngredientesProducto(int id, MateriaPrima materiaPrima,
			Producto producto, Double cantidad) {
		this.id = id;
		this.materiaPrima = materiaPrima;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="ingredientes_producto_id_seq")
    @SequenceGenerator(name="ingredientes_producto_id_seq", sequenceName="ingredientes_producto_id_seq", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne()
	@JoinColumn(name = "id_materia_prima")
	public MateriaPrima getMateriaPrima() {
		return this.materiaPrima;
	}

	public void setMateriaPrima(MateriaPrima materiaPrima) {
		this.materiaPrima = materiaPrima;
	}

	@ManyToOne()
	@JoinColumn(name = "id_producto")
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}
	
	@Column(name = "cantidad")
	public Double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

}
