package ar.com.softarte.model;
// Generated 02-mar-2014 13:46:55 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * MateriaPrima generated by hbm2java
 */
@Entity
@Table(name = "materia_prima", schema = "public")
public class MateriaPrima implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2739289209815477550L;
	
	private int id;
	private TipoMedida tipoMedida;
	private TipoMateriaPrima tipoMateriaPrima;
	private String descripcion;
	private Double medida;
	private Double precio;
	private Integer medidaMinimaStock;
	private Double medidaDisponibleStock;
	
	private Double unidades;

	public MateriaPrima() {
	}

	public MateriaPrima(int id) {
		this.id = id;
	}

	public MateriaPrima(int id, TipoMedida tipoMedida,
			TipoMateriaPrima tipoMateriaPrima, String descripcion,
			Double medida, Double precio,Integer medidaMinimaStock,
			Double medidaDisponibleStock) {
		this.id = id;
		this.tipoMedida = tipoMedida;
		this.tipoMateriaPrima = tipoMateriaPrima;
		this.descripcion = descripcion;
		this.medida = medida;
		this.precio = precio;
		this.medidaMinimaStock = medidaMinimaStock;
		this.medidaDisponibleStock = medidaDisponibleStock;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="materia_prima_id_seq")
    @SequenceGenerator(name="materia_prima_id_seq", sequenceName="materia_prima_id_seq", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne()
	@JoinColumn(name = "id_tipo_medida")
	public TipoMedida getTipoMedida() {
		return this.tipoMedida;
	}

	public void setTipoMedida(TipoMedida tipoMedida) {
		this.tipoMedida = tipoMedida;
	}
	
	@ManyToOne()
	@JoinColumn(name = "id_tipo_materia_prima")
	public TipoMateriaPrima getTipoMateriaPrima() {
		return this.tipoMateriaPrima;
	}

	public void setTipoMateriaPrima(TipoMateriaPrima tipoMateriaPrima) {
		this.tipoMateriaPrima = tipoMateriaPrima;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "medida", precision = 17, scale = 17)
	public Double getMedida() {
		return this.medida;
	}

	public void setMedida(Double medida) {
		this.medida = medida;
	}

	@Column(name = "precio", precision = 17, scale = 17)
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}
	
	@Column(name = "medida_minima_stock")
	public Integer getMedidaMinimaStock() {
		return this.medidaMinimaStock;
	}

	public void setMedidaMinimaStock(Integer medidaMinimaStock) {
		this.medidaMinimaStock = medidaMinimaStock;
	}

	@Column(name = "medida_disponible_stock", precision = 17, scale = 17)
	public Double getMedidaDisponibleStock() {
		return this.medidaDisponibleStock;
	}

	public void setMedidaDisponibleStock(Double medidaDisponibleStock) {
		this.medidaDisponibleStock = medidaDisponibleStock;
	}

	@Transient
	public double getUnidades() {
		return unidades;
	}

	public void setUnidades(double unidades) {
		this.unidades = unidades;
	}
}
