package ar.com.softarte.model;
// Generated 02-mar-2014 13:46:55 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.OrderBy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", schema = "public")
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7656493111179739648L;
	
	private int id;
	private TipoProducto tipoProducto;
	private TipoMedida tipoMedida;
	private String descripcion;
	private String receta;
	private String comentarios;
	private Double medida;
	private int ganancia;
	
	private Set<IngredientesProducto> ingredientesProductos = new HashSet<IngredientesProducto>(
			0);
	
	private double precioCosto;
	private double precioSugerido;

	public Producto() {
	}

	public Producto(int id) {
		this.id = id;
	}

	public Producto(int id, TipoProducto tipoProducto, TipoMedida tipoMedida,
			String descripcion, String receta, String comentarios,
			Double medida, int ganancia,
			Set<IngredientesProducto> ingredientesProductos) {
		this.id = id;
		this.tipoProducto = tipoProducto;
		this.tipoMedida = tipoMedida;
		this.descripcion = descripcion;
		this.receta = receta;
		this.comentarios = comentarios;
		this.medida = medida;
		this.ganancia = ganancia;
		this.ingredientesProductos = ingredientesProductos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="producto_id_seq")
    @SequenceGenerator(name="producto_id_seq", sequenceName="producto_id_seq", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne()
	@JoinColumn(name = "id_tipo_producto")
	public TipoProducto getTipoProducto() {
		return this.tipoProducto;
	}

	public void setTipoProducto(TipoProducto tipoProducto) {
		this.tipoProducto = tipoProducto;
	}

	@ManyToOne()
	@JoinColumn(name = "id_tipo_medida")
	public TipoMedida getTipoMedida() {
		return this.tipoMedida;
	}

	public void setTipoMedida(TipoMedida tipoMedida) {
		this.tipoMedida = tipoMedida;
	}
	
	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "receta")
	public String getReceta() {
		return this.receta;
	}

	public void setReceta(String receta) {
		this.receta = receta;
	}

	@Column(name = "comentarios")
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "medida", precision = 17, scale = 17)
	public Double getMedida() {
		return this.medida;
	}

	public void setMedida(Double medida) {
		this.medida = medida;
	}

	@Column(name = "ganancia")
	public int getGanancia() {
		return this.ganancia;
	}

	public void setGanancia(int ganancia) {
		this.ganancia = ganancia;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "producto")
	@OrderBy(clause = "materiaPrima")
	@JsonIgnore
	public Set<IngredientesProducto> getIngredientesProductos() {
		return this.ingredientesProductos;
	}

	public void setIngredientesProductos(
			Set<IngredientesProducto> ingredientesProductos) {
		this.ingredientesProductos = ingredientesProductos;
	}

	@Transient
	public double getPrecioCosto() {
		return precioCosto;
	}

	public void setPrecioCosto(double precioCosto) {
		this.precioCosto = precioCosto;
	}
	
	@Transient
	public double getPrecioSugerido() {
		return precioSugerido;
	}

	public void setPrecioSugerido(double precioSugerido) {
		this.precioSugerido = precioSugerido;
	}
}
