package ar.com.softarte.model;
// Generated 02-mar-2014 13:46:55 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoProducto generated by hbm2java
 */
@Entity
@Table(name = "tipo_producto", schema = "public")
public class TipoProducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8614358744131144362L;
	
	private int id;
	private String descripcion;

	public TipoProducto() {
	}

	public TipoProducto(int id) {
		this.id = id;
	}

	public TipoProducto(int id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
