package ar.com.softarte.model;
// Generated 02-mar-2014 13:46:55 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMedida generated by hbm2java
 */
@Entity
@Table(name = "tipo_medida", schema = "public")
public class TipoMedida implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3395700552427347132L;
	
	private int id;
	private String descripcion;
	private String abreviatura;

	public TipoMedida() {
	}

	public TipoMedida(int id) {
		this.id = id;
	}

	public TipoMedida(int id, String descripcion, String abreviatura) {
		this.id = id;
		this.descripcion = descripcion;
		this.abreviatura = abreviatura;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "abreviatura", length = 10)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

}
