package ar.com.softarte.model;
// Generated 30-mar-2014 0:23:22 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TipoMateriaPrima generated by hbm2java
 */
@Entity
@Table(name = "tipo_materia_prima", schema = "public")
public class TipoMateriaPrima implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6328269741070362319L;
	private int id;
	private String descripcion;

	public TipoMateriaPrima() {
	}

	public TipoMateriaPrima(int id) {
		this.id = id;
	}

	public TipoMateriaPrima(int id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="tipo_materia_prima_id_seq")
    @SequenceGenerator(name="tipo_materia_prima_id_seq", sequenceName="tipo_materia_prima_id_seq", allocationSize=1)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
